import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from '@/components/nav'
import { Footer } from '@/components/footer'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={'h-full'}>
    <body className={inter.className + ' h-full'}>
    <div className="max-w-2xl mx-auto py-10 px-4">
      <Nav/>
      <main>
        {children}
      </main>
      <Footer/>
    </div>
    </body>
    </html>
  )
}
