import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

import Header from './Header'
import Footer from './Footer'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'BuyABlog',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={'h-full'}>
    <body className={inter.className + ' h-full'}>
    <div className="relative">
      <div className="max-w-3xl mx-auto py-10 px-4">
        <Header />
      {children}
        <Footer />
      </div>
    </div>
    </body>
    </html>
  )
}
